research_task:
  description: >
    Conduct a thorough research about the following topic: {topic}\n
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

question_generator_task:
  description: >
    Take the context you have and generate a research question from it
    by sending the context as the text to the question generator tool.
  expected_output: >
    A research question that can push the {topic} further.
  agent: question_generator

reporting_task:
  description: >
    Review the question you have and think of how you can possibly develop the topic of 
    {topic} by answering this question.
  expected_output: >
    A concise report that summarizes the current research in the {topic} field 
    and provides a clear and concise overview of how it can be developed based on the question.
    Start your response with the question you are answering.
    Formatted as markdown without '```'
  agent: reporting_analyst
